### ISSUE TITLE
NavigationBar: Inconsistent Icon colors

### ISSUE THREAD

**Issue by seblau** [shoutem/extensions#6]
The issue for example occurs in the `shoutem-places` extensions where I get the following result:

![img_6034 copy](https://cloud.githubusercontent.com/assets/3884582/26025888/79856c1e-37f1-11e7-9850-e80b16e8567e.png)

In the Shoutem app builder tough, I specified the following theme setting for the `NavigationBar`:

![screen shot 2017-05-13 at 15 33 25](https://cloud.githubusercontent.com/assets/3884582/26025892/8b2ca374-37f1-11e7-8f3f-fa7ed698b695.png)

I could also spot this kind of issue in some custom extension. The NavigationBar code I am using there looks like the following:

```
import { NavigationBar } from '@shoutem/ui/navigation';

render() {
    return (
      <Screen>
        <NavigationBar hasHistory title="Newsfeed" />
        ...
      </Screen>
    );
}
```

**Comment by Vladimir-Vdovic** [comment]
The builder setting you applied is just for the `Title` component's text color. Right underneath it is a setting for Icon color.

However, I looked into the issue further, and it seems that the theme's color setting is overridden when there is a background image present:

![navbar icon color](https://cloud.githubusercontent.com/assets/28015757/26796124/8e2c8122-4a28-11e7-945c-0f6590f24ffb.jpg)

It does apply overall, eg.:

![navbar icon color 2](https://cloud.githubusercontent.com/assets/28015757/26796129/914cb26e-4a28-11e7-8ff5-d42d64e604a9.jpg)

We'll consider this an enhancement/feature request due to the fact that we do have a theme setting for text that has an image background; `Image overlay text color`.
